version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myProject
    ports:
      - "5433:5432" # pierwszy port - kontener, drugi port - systemowy
                    # są dwa porty, żeby przekierować ruch z portu systemowego na kontenerowy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql